CREATE TABLE IF NOT EXISTS `{dbprefix}green_meta_raw_leads` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `facebook_lead_id` varchar(80) NOT NULL,
  `facebook_page_id` varchar(80) DEFAULT NULL,
  `facebook_form_id` varchar(80) DEFAULT NULL,
  `facebook_ad_id` varchar(80) DEFAULT NULL,
  `facebook_campaign_id` varchar(80) DEFAULT NULL,
  `facebook_adset_id` varchar(80) DEFAULT NULL,
  `form_name` varchar(255) DEFAULT NULL,
  `campaign_name` varchar(255) DEFAULT NULL,
  `ad_name` varchar(255) DEFAULT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `phone_original` varchar(80) DEFAULT NULL,
  `phone_normalized` varchar(40) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  `extra_fields` longtext DEFAULT NULL,
  `raw_payload` longtext DEFAULT NULL,
  `facebook_created_time` datetime DEFAULT NULL,
  `green_client_id` int(11) DEFAULT NULL,
  `green_lead_id` int(11) DEFAULT NULL,
  `process_status` varchar(40) DEFAULT 'pending',
  `process_message` text DEFAULT NULL,
  `imported_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_green_meta_fb_lead_id` (`facebook_lead_id`),
  KEY `idx_green_meta_phone` (`phone_normalized`),
  KEY `idx_green_meta_form` (`facebook_form_id`),
  KEY `idx_green_meta_green_lead` (`green_lead_id`),
  KEY `idx_green_meta_process_status` (`process_status`),
  KEY `idx_green_meta_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `{dbprefix}green_meta_sync_runs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `started_at` datetime DEFAULT NULL,
  `finished_at` datetime DEFAULT NULL,
  `status` varchar(40) DEFAULT 'running',
  `processed` int(11) DEFAULT 0,
  `created` int(11) DEFAULT 0,
  `updated` int(11) DEFAULT 0,
  `duplicate_updates` int(11) DEFAULT 0,
  `errors` int(11) DEFAULT 0,
  `message` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_green_meta_run_started` (`started_at`),
  KEY `idx_green_meta_run_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
